### PR TITLE
Fix crashes and make options work

### PR DESCRIPTION
**Pull request by anzz1**
* Setting option Buff.MessageTimer = 0 actually disables the timed emotes and phrases now
* Fix crash on setting Buff.NumWhispers = 0 (disable whispers)
* Fix crash on setting Buff.NumPhrases = 0 (disable random talk)

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
There is a sql issue, `InhabitType` does not exist.
@acidmanifesto may you can easily fix it?

**Comment by acidmanifesto** [comment]
> There is a sql issue, `InhabitType` does not exist.
> @acidmanifesto may you can easily fix it?

My net is out. But the fix is to remove the inhabit collumn in the query

**Comment by anzz1** [comment]
pushed a change to remove InhabitType

**Comment by acidmanifesto** [comment]
> pushed a change to remove InhabitType

Perfect

**Comment by anzz1** [comment]
pushed another change to replace deprecated config api with new GetOption api to fix build

**Comment by Helias** [comment]
thanks for your PR, unfortunately there are some merge conflicts

**Comment by pangolp** [comment]
@anzz1 Greetings. You have to enable the possibility that we can make commits within the branch, or on the contrary, we will not be able to update it, so that it can be merged. In any case, I will have to create another pull request, and give you the credits within it. But if we can add changes to this same branch, the better, so we finish working on it, and we can merge it.

**Comment by anzz1** [comment]
@pangolp 
image
This box "Allow edits by maintainers" is checked, and I think it's enabled by default?

In any case do whatever you want with this, copy-paste to another PR is completely fine by me if you're having problem updating this one, I'm only here to help and I don't care about credits and such.

**Comment by pangolp** [comment]
> This box "Allow edits by maintainers" is checked, and I think it's enabled by default?
> 
> In any case do whatever you want with this, copy-paste to another PR is completely fine by me if you're having problem updating this one, I'm only here to help and I don't care about credits and such.

I downloaded your branch this morning, I tried to push it and it gave me an error. But if you say it is possible to do it, I will try again. I don't need permissions on the repository, if not, on its restroom, at least on the patch-1 branch, which is where this change is located. I need to push a commit, so I add some changes and we merge it. But I'll try again.

**Comment by pangolp** [comment]
I'll tell you what I wanted to do to make it clearer.

```
git clone https://github.com/anzz1/mod-npc-buffer.git -b patch-1
git push origin patch-1
```

**Comment by anzz1** [comment]
Yes, I understand, I have this feature enabled and this info box says it should work
image
Maybe you don't have write access to azerothcore/mod-npc-buffer ?
Or maybe GitHub is just bugged. I just now unchecked and re-checked the box to also answer the "have you tried turning it off and on again?" question :smile:

**Comment by pangolp** [comment]
> Maybe you don't have write access to azerothcore/mod-npc-buffer ?
> Or maybe GitHub is just bugged. I just now unchecked and re-checked the box to also answer the "have you tried turning it off and on again?" question 😄

No. I tried it this morning, now that I remember at work, where I don't even use ssh. I had to clone it over https. Maybe that was the problem. I'll try again. But it is good to know that you have the option enabled, to rule out errors. I will try again.

**Comment by pangolp** [comment]
Indeed, it was something related to permits. So I'll move on, from now on. Thanks for reviewing it.

**Comment by pangolp** [comment]
Ready, I think that will be enough.
I will wait for the tests to pass, and if they are successful.
I'll merge it, thanks for your contribution.

**Pull request merged**
