### PR TITLE
Port Styx's latest code to AC

### PR DESCRIPTION
**Pull request by gtao725**
All improvements and bugfixes to date by Styx are included.

### CODE REVIEW

**Comment by milestorme** [comment]
tested AC>AzerothCore rev. a0cb2c0b7c66+ 2019-04-13 16:09:19 +0000 (master branch) (Unix, Release) no build errors no console erros works.

**Comment by gtao725** [comment]
I can confirm my previous commit works based on cure res on/off in the config. Have you tried Milestorme?

**Comment by milestorme** [comment]
tested and the rez works but one small problem now, even with buff by level disabled and the spell id set greater blessing of kings wont cast, same if I change the id to blessing of kings it wont cast either, this didn't happen before not sure whats wrong

**Comment by gtao725** [comment]
Just tested with "buff by level" turned off, spell 43223 in the buff list, alliance and horde char levels between 51-59, gm and player, all buffed with greater blessing of kings without any issues. Can merge I believe.

**Comment by milestorme** [comment]
yeah its not working for me

**Comment by gtao725** [comment]
could some one else please also try test this?

**Comment by milestorme** [comment]
Ok this works fine if your set to expansion 2 in worldserver.conf but at expansion 0 it plays up a lot and won’t do certain buffs at certain levels , as long as your set to expansion 2 there’s no issues but expansion 0 there is

**Comment by gtao725** [comment]
ok thx for the info, but let's not go out of the scope too much for these modules in relation to settings elsewhere. Let's merge and raise issues the right way and have those interested in it have a go at fixing/adding features. Right now this buffer module already works and does more than the current AC version.  Let's merge first and then improvise.

**Comment by milestorme** [comment]
Yeah I agree ☝️

**Comment by BarbzYHOOL** [comment]
@gtao725 Thank you for that!!! Merged

**Pull request merged**
